config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'static_pages#main_page'
  resources :tweets
  resources :profiles

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :picture, PicUploader
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user

	validates :content, length:  {maximum: 10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(profile_params)
		@profile.user = current_user
		if @profile.save
			flash[:success] = "You have created a profile"
			redirect_to new_tweet_path
		else
			render 'new'
		end
	end

	def show
		@profile = Profile.find(params[:id])
	end

	def profile_params
		params.require(:profile).permit(:first_name, :picture, :description)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def main_page
		if user_signed_in?
			if current_user.profile
				redirect_to new_tweet_path
			else
				redirect_to new_profile_path
			end
		end
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :authenticate_user!

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
		@tweet.user = current_user 
		if @tweet.save
			flash[:success] = "You have created a tweet"
			redirect_to new_tweet_path
		else
			render 'new'
		end
		
	end

	def index
		@tweets = Tweet.all
	end

	def tweet_params
		params.require(:tweet).permit(:content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Htwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "iLab Twitter",root_path, class:'navbar-brand' %>
     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
	        <li>
	        	<%= link_to "New Tweet", new_tweet_path %>
	        </li>
	        <li>
	        	<%= link_to "News Feed", tweets_path %>
	        </li>
        <% end %>
      </ul>
       <ul class="nav navbar-nav navbar-right">
        <li>
			<% if user_signed_in? %>
				<%= link_to "Log out", destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to "Sign in", new_user_session_path %>
			<% end %>
		</li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? && current_user.profile %>
              <li><%= link_to "my profile", profile_path(current_user.profile)  %></li>
            <% end %>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>




<body>
<div class ="container">	

	<% flash.each do |key,value|  %>
	<div class = "alert alert-<%=key%>">		
		<%= value %>
	</div>
	<% end %>

	<%= yield %>
</div>

</body>
</html>

app/views/profiles/new.html.erb
<%= simple_form_for @profile do |f| %>
	<%= f.input :picture %>
	<%= f.input :first_name %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/profiles/show.html.erb
<%= image_tag @profile.picture, size: '300x300' %>

<%= @profile.first_name %>
<%= @profile.description %>

app/views/static_pages/main_page.html.erb
This is the main page

app/views/tweets/index.html.erb
<ul class="list-group">
	<% @tweets.each do |tweet| %>
		<li class="list-group-item">
		<%= tweet.content %> | <%= link_to "tweet.user.profile.first_name, profile_path(tweet.user.profile) %>
		</li>
	<% end %>
</ul>

app/views/tweets/new.html.erb
<%= simple_form_for @tweet do |f| %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>